### ISSUE TITLE
Find suitable parameters

### ISSUE THREAD

**Issue by adrian-pace** [adrian-pace/FROG-analytics#1]
Try to tune

edit size
time delay before new operation
...

**Comment by lbaligand** [comment]
The synchronous/async delay time needs to be augmented. Only one pad over 150 was in sync.

**Comment by adrian-pace** [comment]
can I close this ?

**Comment by lbaligand** [comment]
Yeah after some analysis and discussion we will choose a length of edit of 15 characters and 20 sec of delay to change of Operation.
