### ISSUE TITLE
live feeding restructure

### ISSUE THREAD

**Issue by adrian-pace** [adrian-pace/FROG-analytics#10]

**Comment by adrian-pace** [comment]
According to #7 time analysis

Time analysis :
On stian logs 627 pads. Everything.
(times are in seconds)

parsing: 30.954002618789673
parsing aTextes (only in dev) 0.3829975128173828
operation_builder total 46.490999937057495
operation building time 8.0290367603302
paragraph construction time 32.98596119880676
Operation classification time 0.2220005989074707
Operation context time 4.018999338150024

So we will build a system that wait for new input in the parser.
If new input :
- parse it
- update operation construction
- update paragraphs (do smth about the operation per paragraphs that might change
- rebuild context. 
- update visualizations (saving them to files)
- update colored text.
- Repeat.

We could then build a simple client that display the plots/metrics when they are updated

**Comment by adrian-pace** [comment]
@pykcel
well. it's starting to work: 

the video is of bad quality, but still, it's pretty cool
https://drive.google.com/file/d/149OOH5jS7Qf_yBZfEo-T4NEwTdXf_5CV/view?usp=sharing

**Comment by lbaligand** [comment]
Awesome! Well done 🥇

**Comment by houshuang** [comment]
Looks awesome. Is this done by hooking directly to the database and reading from it? I'm still thinking about how we can best integrate this in FROG.

**Comment by adrian-pace** [comment]
This one is done directly by parsing the file. However the methods for hooking up with the database and querying it worked in the non-live version so it should be realtively straight forward to modify them. I already have a draft that I need to test on my linux machine.

A few options are for example storing the data or plots to a file and FROG could load them. We could also setup a tcp connection that send the information to FROG such as metrics or even images.
