### ISSUE TITLE
pad.alternating_score bug

### ISSUE THREAD

**Issue by adrian-pace** [adrian-pace/FROG-analytics#12]
the following line doesn't work if main_authors = 1 (if there is only the admin writing)
len(main_authors) - 1

**Comment by lbaligand** [comment]
Yes, if there is only one paragraph, it can't alternate, then we return 0, i'll fix it, thanks for pointing it out

**Comment by adrian-pace** [comment]
no, I meant if len(main_authors) = 1, you divide by zero so it throws an error
