### ISSUE TITLE
Metrics not working on stian logs

### ISSUE THREAD

**Issue by lbaligand** [adrian-pace/FROG-analytics#9]
Synchronous_in_pad is not initialized

**Comment by lbaligand** [comment]
So the issue is that in stian logs, some jump (we have to investigate which ones) doesn't create a paragraph and when we create a context we iterate over all operations of all paragraphs (more efficient in complexity). I temporally fixed the issue by creating an empty context for those exceptional cases but it might be an issue due to paragraph.
The metrics works fine now but it might not be super robust...

**Comment by adrian-pace** [comment]
please send me the pad and elem_op operation such as abs_position and its timestamp

**Comment by lbaligand** [comment]
Pad: 753268753268753268753268753268753268

Op:
Author:Etherpad_admin
Position: From 262 to 263
Written: from 1438860844402.1304 to 1438860844402.1304
With 1 elementary operations
Type: jump
Context: {}

The full logs until the error
PAD: 753268753268753268753268753268753268
`
COLORED TEXT BY AUTHOR
1. How will your lesson embrace diversity in the classroom (i.e., as a positive feature, meaning that your lesson is better off for having diversity, and its not a problem to overcome!)  How will it help ensure equity for the various students in the classroom?
Treat all students as individuals with unique strengths, weaknesses, and needs  rather than as generalized representatives of particular racial, ethnic or cultural  groups. 
 Employ a variety of teaching styles to respond to the needs of diverse learners.• Create an open classroom that values the experiences and perspectives of all students. Articulate early in the lesson that as teachers we are committed to meeting the needs of all students and that we are open to conversations about how to help them learn
With the help of technlogy, every child can have a say and feel confident behind the screen. Students will have a chance to see other people's points of view. And this is quite thrilling and exciting.

2.  How will student progress be assessed?  Try to include the technology-enhanced parts of your lesson into the assessment plan. For example, if students are making drawings or concept maps - how will those artifacts be used for purposes of assessment (formative or summative)?
The following are a few representative examples of formative assessments:
*Questions that we as  teachers posme to individual students and groups of students during the learning process to determine what specific concepts or skills they may be having trouble with. A wide variety of intentional questioning strategies may be employed, such as phrasing questions in specific ways to elicit more useful responses.
*Specific, detailed, and constructive feedback that teachers provide on student work, such as journal entries, essays, worksheets, research papers, projects, ungraded quizzes, lab results, or works of art, design, and performance. The feedback may be used to revise or improve a work product, for example.
*“Exit slips” or “exit tickets” that quickly collect student responses to a teacher’s questions at the end of a lesson or class period. Based on what the responses indicate, the teacher can then modify the next lesson to address concepts that students have failed to comprehend or skills they may be struggling with. “Admit slips” are a similar strategy used at the beginning of a class or lesson to determine what students have retained from previous learning experiences.
*Self-assessments that ask students to think about their own learning process, to reflect on what they do well or struggle with, and to articulate what they have learned or still need to learn to meet course expectations or learning standards.
*Peer assessments that allow students to use one another as learning resources. For example, “workshopping” a piece of writing with classmates is one common form of peer assessment, particularly if students follow a rubric or guidelines provided by the teacher.

Summative Assessments
 Demonstrations of learning or other forms of “performance assessment,” such as portfolios of student work that are collected over time and evaluated by teachers or capstone projects that students work on over extended periods of time and that they present and defend at the conclusion of a school year or their high school education.


3. How will the teacher ensure that this lesson goes as planned?  What kinds of hints would you give to any teacher who was going to run this lesson? How should the teacher use her/his time in the classroom most effectively, while the kids are using the technology (hint: its not just to make sure the computers are all working and kids are staying on-task!) What kinds of interactions should the pursue with students?
First the teacher needs to be well informed on the subject matter at hand.  The hints I would give a teacher who is starting this lesson would be:
    Know your topic
    Have worksheets prepared before start of lesson
    Know which group works with what group.
    Explain the task fully to the students befoire starting
    Be familiar with the knowledge of small students in the group.
    Whilst the students are working the teacher could be using an IPAD to film different groups so trhat she could review the learning after the lesson-collaboration, feedback, questioning and tasks of students.
    Regards computer skills the teacher could have a checklist of computer skills that children need to know and she could mark off the skill as or when aquired by the student working on the task.
    

SCORES
User proportion per paragraph score 0.00417355435079
Proportion score: 0.310361756348
Author:Etherpad_admin
Position: From 0 to 260
Written: from 1438860844402 to 1438860844402
With 1 elementary operations
Type: paste
Context: {'synchronous_in_paragraph_with': [], 'proportion_pad': 0.05736981465136805, 'proportion_paragraph': 1.0, 'synchronous_in_pad_with': [], 'first_op_break': False, 'first_op_day': True, 'synchronous_in_paragraph': False, 'synchronous_in_pad': False}
Author:Etherpad_admin
Position: From 260 to 261
Written: from 1438860844402.0435 to 1438860844402.0435
With 1 elementary operations
Type: jump
Context: {'synchronous_in_paragraph_with': [], 'proportion_pad': 0.0002206531332744925, 'proportion_paragraph': 1.0, 'synchronous_in_pad_with': [], 'first_op_break': False, 'first_op_day': False, 'synchronous_in_paragraph': False, 'synchronous_in_pad': False}
Author:Etherpad_admin
Position: From 261 to 262
Written: from 1438860844402.087 to 1438860844402.087
With 1 elementary operations
Type: jump
Context: {'synchronous_in_paragraph_with': [], 'proportion_pad': 0.0002206531332744925, 'proportion_paragraph': 1.0, 'synchronous_in_pad_with': [], 'first_op_break': False, 'first_op_day': False, 'synchronous_in_paragraph': False, 'synchronous_in_pad': False}
Author:Etherpad_admin
Position: From 262 to 263
Written: from 1438860844402.1304 to 1438860844402.1304
With 1 elementary operations
Type: jump
Context: {}
Traceback (most recent call last):
  File "C:/Users/Louis/Documents/EPFL/semesterProject/FROG-analytics.git/analytics/main_stian_logs.py", line 73, in <module>
    print('Synchronous score:', pad.sync_score()[0])
  File "C:\Users\Louis\Documents\EPFL\semesterProject\FROG-analytics.git\analytics\Pad.py", line 643, in sync_score
    if op.context['synchronous_in_pad']:
KeyError: 'synchronous_in_pad'`

**Comment by adrian-pace** [comment]
can you sed me the **Elementary operation** that you said was not creating the new paragraph

**Comment by lbaligand** [comment]
Operation:add
Position:262
Text to add:

Line number:0
Position inline:0
Author:Etherpad_admin
Timestamp:1438860844402.1304
Pad Name:753268753268753268753268753268753268
Revs:0
Original changeset:Z:1>qv|b+qv$1. How will your lesson embrace diversity in the classroom (i.e., as a positive feature, meaning that your lesson is better off for having diversity, and its not a problem to overcome!)  How will it help ensure equity for the various students in the classroom?




2.  How will student progress be assessed?  Try to include the technology-enhanced parts of your lesson into the assessment plan. For example, if students are making drawings or concept maps - how will those artifacts be used for purposes of assessment (formative or summative)?




3. How will the teacher ensure that this lesson goes as planned?  What kinds of hints would you give to any teacher who was going to run this lesson? How should the teacher use her/his time in the classroom most effectively, while the kids are using the technology (hint: its not just to make sure the computers are all working and kids are staying on-task!) What kinds of interactions should the pursue with students?

Editor:None
Belong to Operation:Author:Etherpad_admin
Position: From 262 to 263
Written: from 1438860844402.1304 to 1438860844402.1304
With 1 elementary operations
Type: jump
Context: {}

**Comment by adrian-pace** [comment]
thanks, will have a look and keep you posted

**Comment by adrian-pace** [comment]
Are you sure ? because here it does create the paragraph. It's an empty paragraph because it's a new line. Don't know if that's the problem.
![image](https://user-images.githubusercontent.com/11006241/33380182-877060ce-d51a-11e7-95c2-62b45673799b.png)

**Comment by lbaligand** [comment]
Right but are you sure, it is added to the pad paragraphs. Print of the paragraphs of the pad:
![capture](https://user-images.githubusercontent.com/10983399/33380588-e2331956-d51b-11e7-9212-d04bf62ef4e7.JPG)
There should be a pragrah with "from: 262 etc.." right?

**Comment by adrian-pace** [comment]
get the length with elem_ops instead of operation as discussed
